name: Release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@rodano'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Typescript compiler
        run: npm run tsc

      # retrieve version
      - name: Get the version from the Git reference
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      # create a GitHub release
      - name: Create a GitHub release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} ${{ contains(steps.get_version.outputs.VERSION, 'rc') && '--prerelease' || '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # publish package
      - name: Publish in repository
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
